src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $company;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 255)]
    private $zipcode;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\Column(type: 'string', length: 255)]
    private $country;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $telephone;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $vat_number;

    #[ORM\Column(type: 'boolean')]
    private $delivery;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'adresses')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

     #[Pure] public function  __toString()
    {
          return $this->getFirstname().' '.$this->getLastname().'[br]'.$this->getAdresse().'[br]'.$this->getZipcode().' - '.$this->getCity().'[br]';
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getVatNumber(): ?string
    {
        return $this->vat_number;
    }

    public function setVatNumber(?string $vat_number): self
    {
        $this->vat_number = $vat_number;

        return $this;
    }

    public function getDelivery(): ?bool
    {
        return $this->delivery;
    }

    public function setDelivery(bool $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/AdresseType.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdresseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname',TextType::class, options: [
                'label' => false,
                'attr'=> [
                    'placeholder'=> "Firstname",
                    'class' => "input_forms"]
            ])
            ->add('lastname',TextType::class, options: [
                'label' => false,
                'attr'=> [
                    'placeholder'=> "Lastname",
                    'class' => "input_forms"]
            ])
            ->add('company',TextType::class, options: [
                'label' => false,
                'required' => false,
                'attr'=> [
                    'placeholder'=> "Company",
                    'class' => "input_forms"]
            ])
            ->add('vat_number',TextType::class, options: [
                'label' => false,
                'required' => false,
                'attr'=> [
                    'placeholder'=> "Vat number",
                    'class' => "input_forms"]
            ])
            ->add('adresse',TextType::class, options: [
                'label' => false,
                'attr'=> [
                    'placeholder'=> "Address",
                    'class' => "input_forms"]
            ])
            ->add('zipcode',TextType::class, options: [
                'label' => false,
                'attr'=> [
                    'placeholder'=> "Zipcode",
                    'class' => "input_forms"]
            ])
            ->add('city',TextType::class, options: [
                'label' => false,
                'attr'=> [
                    'placeholder'=> "City",
                    'class' => "input_forms"]
            ])
            ->add('country', CountryType::class, options: [
                'label' => false,
                'attr'=> [
                    'placeholder'=> "Country",
                    'class' => "input_forms"]
            ])
            ->add('telephone',TextType::class, options: [
                'label' => false,
                'required' => false,
                'attr'=> [
                    'placeholder'=> "Phone number",
                    'class' => "input_forms"]
            ])


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adresse::class,
        ]);
    }
}

src/Controller/AdresseController.php
<?php

namespace App\Controller;
use App\Entity\Adresse;
use App\Form\AdresseType;
use App\Repository\AdresseRepository;
use App\Services\Cart;
use App\Services\DefaultAdresseService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/adresse')]
class AdresseController extends AbstractController
{
    // j'appelle ma classe defaultAdresseService pour pouvoir appeler les fonctions qu'il y a dedans
    private DefaultAdresseService $defaultAdresseService;

    // je veux initialiser une fois notre service avec une methode construct
    // en gros je vérifie les infos avant de faire quoi que se soit
    public function __construct(DefaultAdresseService $defaultAdresseService){
        $this->defaultAdresseService = $defaultAdresseService;
    }

    // J'ai supprimé la vue adresse-index, car l'Administrateur ne désirait pas voir la liste des adresses de tout le monde.

     //CREER UNE NOUVELLE ADRESSE UTILISATEUR
    #[Route('/new_adresse', name: 'adresse_new', methods: ['GET', 'POST'])]
    public function new(Cart $cart, Request $request, EntityManagerInterface $entityManager): Response
    {
        // je récupère l'utilisateur
        $user =$this->getUser();
        // Je crée un nouvel objet adresse.
        $adresse = new Adresse();
        // je crée le formulaire de creation d'adresse
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);
        //si le formulaire est envoyé et valide
        if ($form->isSubmitted() && $form->isValid()) {
            //j'associe l'adresse à l'id de l'user connecté en faisant un set.
            $adresse->setUserId($user);
            // j'appelle ma fonction globale : defaultAdresseService et ma methode selectByDefault et je lui passe l'adresse et l'user
            // à la creation d'une adresse la fonction selectByDefault va verifier grace à la methode isDefaultAdresse s'il y a deja une adresse par default dans la BDD
            // s'il n'y en a pas l'adresse sera passé par default
            // s'il y a deja une adresse par default dans la BDD elle créera juste une adresse default:false
            $this->defaultAdresseService->selectByDefault($adresse, $user);

            $entityManager->persist($adresse);
            $entityManager->flush();
            //Je renvoie l'utilisateur sur sa vue profil s'il n'a pas de produit dans son panier.
            // Si il a des produits dans son panier je le redirige vers le panier.
            if (!empty($cart->getCart())){
                return $this->redirectToRoute('payment');
            }
            return $this->redirectToRoute('profil');
        }

        return $this->renderForm('adresse/new.html.twig', [
            'adresse' => $adresse,
            'form' => $form,

        ]);
    }

    // VOIR ADRESSE UTILISATEUR
    #[Route('/adresse_show/{id}', name: 'adresse_show', methods: ['GET'])]
    public function show(Adresse $adresse): Response
    {
        // je dois protéger mon code, car j'ai fait des crud mais je dois les rendrent propres a chaque utilisateur :
        // 1ère étape : je récupère l'user connecté
        $userConnected=$this->getUser();
        // 2ᵉ étape : je récupère l'adresse de l'user connecté
        $userAdresse=$adresse->getUserId();
        // 3ᵉ étape : je fais une comparaison :
        // si l'user connecté est différent de l'id de l'user à qui appartient l'adresse je le déconnecte.
        // Car c'est peut-être quelqu'un de mal intentionné.
        if ($userConnected != $userAdresse){
            return $this->redirectToRoute('logout');
        }
        // Si l'id de l'user connecté correspond a l'id de l'user de l'adresse : tout est ok !
        // je lui montre son adresse
        return $this->render('adresse/show.html.twig', [
            'adresse' => $adresse,

        ]);
    }

    // EDITER ADRESSE UTILISATEUR
    #[Route('/adresse_edit/{id}', name: 'adresse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Adresse $adresse, EntityManagerInterface $entityManager): Response
    {
        // Même principe qu'avec adresse-show
        // je dois protéger mon code, car j'ai fait des crud mais je dois les rendrent propres a chaque utilisateur :
        // 1ère étape : je récupère l'user connecté
        $userConnected=$this->getUser();
        // 2ᵉ étape : je récupère l'adresse de l'user connecté
        $userAdresse=$adresse->getUserId();
        // 3ᵉ étape : je fais une comparaison :
        // si l'user connecté est différent de l'id de l'user à qui appartient l'adresse je le déconnecte.
        // Car c'est peut-être quelqu'un de mal intentionné.
        if ($userConnected != $userAdresse){
            return $this->redirectToRoute('logout');
        }
        // Si l'id de l'user connecté correspond a l'id de l'user de l'adresse : tout est ok !
        // je lui montre son adresse
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('profil', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse/edit.html.twig', [
            'adresse' => $adresse,
            'form' => $form,

        ]);
    }

    // SUPPRIMER ADRESSE UTILISATEUR
    #[Route('/adresse_delete/{id}', name: 'adresse_delete', methods: ['POST'])]
    public function delete(Request $request, Adresse $adresse, EntityManagerInterface $entityManager): Response
    {
        
        // je dois protéger mon code, car j'ai fait des cruds mais je dois les rendrent propres a chaque utilisateur
        // je récupère l'user connecté
        $userConnected=$this->getUser();
        // je récupère l'adresse de l'user connecté
        $userAdresse=$adresse->getUserId();
        // et je fais une comparaison :
        // si l'user connecté est différent de l'id de l'user a qui appartient l'adresse je le déconnecte.
        if ($userConnected != $userAdresse){
            return $this->redirectToRoute('logout');
        }
        // sinon je lui permet de supprimer son adresse
        if ($this->isCsrfTokenValid('delete'.$adresse->getId(), $request->request->get('_token'))) {
            $entityManager->remove($adresse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('profil', [], Response::HTTP_SEE_OTHER);
    }

    //SELECTIONNER ADRESSE PAR DEFAULT
    // cette fonction est créée pour pouvoir sélectionner son adresse par défaut dans la vue public
    #[Route('/adresse_select', name: 'adresse_select', methods: ['GET'])]
    public function index(AdresseRepository $adresseRepository): Response
    {

        // je récupère l'utilisateur pour pouvoir voir toutes les infos en relation avec cet utilisateur
        // si je ne le fais pas je vois toutes les adresses de tout le monde.
        $user=$this->getUser();
        return $this->render('adresse/index.html.twig', [
            'adresses' => $adresseRepository->findBy(['user_id' => $user]),
        ]);
    }
 
    
}

templates/adresse/_delete_form.html.twig
<form method="post" action="{{ path('adresse_delete', {'id': adresse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adresse.id) }}">
    <button class="button_inset m-8">Delete</button>
</form>

templates/adresse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adresse
{% endblock %}

{% block body %}
    <h1>Edit my address</h1>

    <div class="forms_container">
        <div class="col">
                {{ include('adresse/_form.html.twig', {'button_label': 'Update'}) }}
                <br>
                <a class="button_inset" href="{{ path('profil') }}">Back to profil</a>
        </div>
    </div>



{% endblock %}

templates/adresse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse index
{% endblock %}

{% block body %}
<article class="dash_contain">

<h1>All Users'addresses :</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Firstname</th>
				<th>Lastname</th>
				<th>Company</th>
				<th>Vat_number</th>
				<th>Address</th>
				<th>Zipcode</th>
				<th>City</th>
				<th>Country</th>
				<th>Telephone</th>

			</tr>
		</thead>
		<tbody>
			{% for adresse in adresses %}
				<tr>
					<td>{{ adresse.id }}</td>
					<td>{{ adresse.firstname }}</td>
					<td>{{ adresse.lastname }}</td>
					<td>{{ adresse.company }}</td>
					<td>{{ adresse.vatNumber }}</td>
					<td>{{ adresse.adresse }}</td>
					<td>{{ adresse.zipcode }}</td>
					<td>{{ adresse.city }}</td>
					<td>{{ adresse.country }}</td>
					<td>{{ adresse.telephone }}</td>

					<td>
						<a class="button_dash" href="{{ path('adresse_show', {'id': adresse.id}) }}">
							SHOW
						</a>
					<a class="button_dash" href="{{ path('adresse_edit', {'id': adresse.id}) }}">
							EDIT
						</a>
					</td>
					<td></td>
				</tr>
			{% else %}
				<tr>
					<td colspan="11">There is no addresses registered yet !</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</article>
	<h4 class="mobile_responsive">
		Please use a Desktop version to access to your admin panel !
	</h4>
	<aside class="responsive_table">
		{% for adresse in adresses %}
			<br>
			<div class="row">
				<h4>Id</h4> - <h4>{{ adresse.id }}</h4>
			</div>
			<div class="row">
				<h4>Firstname</h4> - <h4>{{ adresse.firstname }}</h4>
			</div>
			<div class="row">
				<h4>Lastname</h4> - <h4>{{ adresse.lastname }}</h4>
			</div>
			<div class="row">
				<h4>Company</h4> - <h4>{{ adresse.company }}</h4>
			</div>
			<div class="row">
				<h4>Vat Number</h4> - <h4>{{ adresse.vatNumber }}</h4>
			</div>
			<div class="row">
				<h4>Address</h4> - <h4>{{ adresse.adresse }}</h4>
			</div>
			<div class="row">
				<h4>Zipcode</h4> - <h4>{{ adresse.zipcode }}</h4>
			</div>
			<div class="row">
				<h4>City</h4> - <h4>{{ adresse.city }}</h4>
			</div>
			<div class="row">
				<h4>Country</h4> - <h4>{{ adresse.country }}</h4>
			</div>
			<div class="row">
				<h4>Telephone</h4> - <h4>{{ adresse.telephone }}</h4>
			</div>
			<div class="row">
				<h4>Actions</h4> - <a class="button_dash" href="{{ path('adresse_show', {'id': adresse.id}) }}"> SHOW </a> - <a class="button_dash" href="{{ path('adresse_edit', {'id': adresse.id}) }}"> EDIT </a>
			</div>
			<br>
			<hr>
		{% else %}
			<p>There is no addresses registered yet !</p>
		{% endfor %}
	</aside>
{% endblock %}

templates/adresse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adresse{% endblock %}

{% block body %}
    <h1>Add Address</h1>
    <div class="forms_container">
            <div class="col">
                {{ include('adresse/_form.html.twig') }}
                <a class="button_inset" href="{{ path('profil') }}">Back to profil</a>
            </div>
    </div>


{% endblock %}

templates/adresse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse{% endblock %}

{% block body %}
    <h1>Adresse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adresse.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ adresse.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ adresse.lastname }}</td>
            </tr>
            <tr>
                <th>Company</th>
                <td>{{ adresse.company }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ adresse.adresse }}</td>
            </tr>
            <tr>
                <th>Zipcode</th>
                <td>{{ adresse.zipcode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ adresse.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ adresse.country }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ adresse.telephone }}</td>
            </tr>
            <tr>
                <th>Vat_number</th>
                <td>{{ adresse.vatNumber }}</td>
            </tr>
        </tbody>
    </table>
    <a class="button m-20" href="{{ path('adresse_edit', {'id': adresse.id}) }}">EDIT</a>

    <a class="button_inset" href="{{ path('adresse_index') }}">back to list</a>
    <br>

    {{ include('adresse/_delete_form.html.twig') }}


{% endblock %}