src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $reference;

    #[ORM\Column(type: 'datetime')]
    private $date_order;

    #[ORM\Column(type: 'text')]
    private $adresse;

    #[ORM\OneToMany(mappedBy: 'order_id', targetEntity: DetailOrder::class, orphanRemoval: true)]
    private $detailOrders;

    #[ORM\Column(type: 'boolean')]
    private $delivery;

    #[ORM\Column(type: 'float', nullable: true)]
    private $voucher;

    #[ORM\Column(type: 'float')]
    private $totalPrice;

    #[ORM\Column(type: 'string', length: 255)]
    private $stripeSessionId;

    public function __construct()
    {
        $this->detailOrders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getDateOrder(): ?\DateTimeInterface
    {
        return $this->date_order;
    }

    public function setDateOrder(\DateTimeInterface $date_order): self
    {
        $this->date_order = $date_order;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return Collection|DetailOrder[]
     */
    public function getDetailOrders(): Collection
    {
        return $this->detailOrders;
    }

    public function addDetailOrder(DetailOrder $detailOrder): self
    {
        if (!$this->detailOrders->contains($detailOrder)) {
            $this->detailOrders[] = $detailOrder;
            $detailOrder->setOrderId($this);
        }

        return $this;
    }

    public function removeDetailOrder(DetailOrder $detailOrder): self
    {
        if ($this->detailOrders->removeElement($detailOrder)) {
            // set the owning side to null (unless already changed)
            if ($detailOrder->getOrderId() === $this) {
                $detailOrder->setOrderId(null);
            }
        }

        return $this;
    }

    public function getDelivery(): ?bool
    {
        return $this->delivery;
    }

    public function setDelivery(bool $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    public function getVoucher(): ?float
    {
        return $this->voucher;
    }

    public function setVoucher(?float $voucher): self
    {
        $this->voucher = $voucher;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(float $totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripeSessionId;
    }

    public function setStripeSessionId(string $stripeSessionId): self
    {
        $this->stripeSessionId = $stripeSessionId;

        return $this;
    }



}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use App\Entity\Order;
use Doctrine\DBAL\Driver\Mysqli\Initializer\Options;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $options['user'];
        $builder
            ->add ('adresses', EntityType::class, [
                'mapped' => false,
                'label' => 'Choose your delivery address',
                'required' => true,
                'class' => Adresse::class,
                'choices' => $user->getAdresses(),
                'multiple' => false,
                'expanded' => true
            ])
        ->add('submit', SubmitType::class, [
            'label' => "Checkout",
            'attr' => [
                'class' => 'button mt-20'
            ]
        ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
            'user' => array()
        ]);
    }
}

src/Controller/Admin/OrderController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/order')]
class OrderController extends AbstractController
{
    #[Route('/order_index', name: 'order_index', methods: ['GET'])]
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),

        ]);
    }

    #[Route('/new_order', name: 'order_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/new.html.twig', [
            'order' => $order,
            'form' => $form,

        ]);
    }

    #[Route('/order_show{id}', name: 'order_show', methods: ['GET'])]
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,

        ]);
    }

    // cette fonction n'est appeler nulle part 
    #[Route('/{id}/order_edit', name: 'order_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/edit.html.twig', [
            'order' => $order,
            'form' => $form,

        ]);
    }

    // cette fonction n'est appeler nulle part 
    #[Route('/order_delete{id}', name: 'order_delete', methods: ['POST'])]
    public function delete(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('order_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="button_inset m-8">Delete</button>
</form>

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>
<section>
    <div class="card_dash">
    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}
        <div class="buttons_panel">
            <div class="row">
        {{ include('order/_delete_form.html.twig') }}

    <a class="button_inset_back" href="{{ path('order_index') }}">back to list</a>


    </div>
    </div>
    </div>
</section>
{% endblock %}

templates/order/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Orders{% endblock %}

{% block contain %}
<article class="dash_contain">
<h2>Orders</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reference</th>
                <th>Date_order</th>
                <th>Details</th>
                <th>Address</th>
                <th>Voucher</th>
                <th>Total</th>
                <th>Actions</th>

            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.reference }}</td>
                <td>{{ order.dateOrder ? order.dateOrder|date('Y-m-d H:i:s') : '' }}</td>
                <td>{% for orderDetail in order.detailOrders %}
                        <p>{{ orderDetail.title }}</p>
                        <p>x {{ orderDetail.quantity }}</p>
                        <p>{{ orderDetail.price }} €</p>
                    {% endfor %}</td>
                <td>{{ order.adresse|raw }}</td>
                <td>{{ order.voucher }} %</td>
                <td>{{ order.totalPrice }} €</td>
                <td>
                    <a class="button_dash" href="{{ path('order_show', {'id': order.id}) }}">SHOW</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</article>
    <h4 class="mobile_responsive">
        Please use a Desktop version to access to your admin panel !
    </h4>

    <aside class="responsive_table">
        {% for order in orders %}
            <br>
            <div class="row">
                <h4>Id</h4> - <h4>{{ order.id }}</h4>
            </div>
            <div class="row">
                <h4>Reference</h4> - <h4>{{ order.reference }}</h4>
            </div>
            <div class="row">
                <h4>Date Order</h4> - <h4>{{ order.dateOrder ? order.dateOrder|date('Y-m-d H:i:s') : '' }}</h4>
            </div>
            <div class="row">
                <h4>Address</h4> - <h4>{{ order.adresse }}</h4>
            </div>
            <div class="row">
                <h4>Voucher</h4> - <h4>- {{ order.voucher }} %</h4>
            </div>
            <div class="row">
                <h4>Total</h4> - <h4>{{ order.totalPrice }}€</h4>
            </div>
            <div class="row">
                <h4>Actions</h4> - <a class="button_dash" href="{{ path('order_show', {'id': order.id}) }}">SHOW</a>
            </div>
            <br>
            <hr>
        {% else %}
            <p>no records found</p>
        {% endfor %}
    </aside>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>
<section>
    <div class="card_dash">
    {{ include('order/_form.html.twig') }}

    <a class="button_inset_back" href="{{ path('order_index') }}">back to list</a>
    </div>
</section>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
<div class="forms_container">
    <h1>Detail of the order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ order.reference }}</td>
            </tr>
            <tr>
                <th>Details</th>
                <td>{% for orderDetail in order.detailOrders %}
                        <p>{{ orderDetail.title }}</p>
                        <p>x {{ orderDetail.quantity }}</p>
                        <p>{{ orderDetail.price }} €</p>
                    {% endfor %}</td>
            </tr>
            <tr>
                <th>Date_order</th>
                <td>{{ order.dateOrder ? order.dateOrder|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ order.adresse|raw }}</td>
            </tr>
            <tr>
                <th>Voucher</th>
                <td>{{ order.voucher }} %</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ order.totalprice }} €</td>
            </tr>
            <tr>
        </tbody>
    </table>
    <div class="button-desk">
        <a class="button_inset" href="{{ path('order_index') }}">back to list</a>
    </div>
</div>


    <aside class="responsive_table">
            <br>
            <div class="row">
                <h4>Id</h4> - <h4>{{ order.id }}</h4>
            </div>
            <div class="row">
                <h4>Reference</h4><h4>{{ order.reference }}</h4>
            </div>
            <div class="row">
                <h4>Date_order</h4><h4>{{ order.dateOrder ? order.dateOrder|date('Y-m-d H:i:s') : '' }}</h4>
            </div>
            <div class="row">
                <h4>Adresse</h4> - <h4>{{ order.adresse }}</h4>
            </div>
        <div class="row">
            <h4>Voucher</h4> - <h4> - {{ order.voucher }} %</h4>
        </div>
        <div class="row">
            <h4>Total</h4> - <h4>{{ order.totalPrice }} €</h4>
        </div>

            <br>
            <hr>

        <div class="button-mob mt-30">
            <a class="button_inset" href="{{ path('order_index') }}">back to list</a>
        </div>
    </aside>
{% endblock %}